[build]
  command = "npm ci && npx gatsby clean && npx gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"
  NVM_VERSION = "1.1.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200